name: Agent CI

on:
  push:
    paths:
      - 'agent/**'
      - '.github/workflows/agent-ci.yaml'
  pull_request:
    paths:
      - 'agent/**'
      - '.github/workflows/agent-ci.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          cd agent
          npm test
